#call adb kill-server
#call adb start-server
call adb shell pm disable-user --user 0 com.android.bookmarkprovider
call adb shell pm disable-user --user 0 com.android.providers.partnerbookmarks
call adb shell pm disable-user --user 0 com.aura.oobe.samsung
call adb shell pm disable-user --user 0 com.microsoft.office.officehubrow
call adb shell pm disable-user --user 0 com.microsoft.office.outlook
call adb shell pm disable-user --user 0 com.microsoft.skydrive
call adb shell pm disable-user --user 0 com.mygalaxy
call adb shell pm disable-user --user 0 com.netflix.mediaclient
call adb shell pm disable-user --user 0 com.netflix.partner.activation
call adb shell pm disable-user --user 0 com.opera.max.oem
call adb shell pm disable-user --user 0	com.android.bips
call adb shell pm disable-user --user 0	com.android.bookmarkprovider
call adb shell pm disable-user --user 0	com.android.certinstaller
call adb shell pm disable-user --user 0	com.android.dreams.basic
call adb shell pm disable-user --user 0	com.android.egg
call adb shell pm disable-user --user 0	com.android.internal.display.cutout.emulation.corner
call adb shell pm disable-user --user 0	com.android.internal.display.cutout.emulation.waterfall
call adb shell pm disable-user --user 0	com.android.providers.partnerbookmarks
call adb shell pm disable-user --user 0	com.android.simappdialog
call adb shell pm disable-user --user 0	com.android.traceur
call adb shell pm disable-user --user 0	com.android.wallpapercropper
call adb shell pm disable-user --user 0	com.aura.oobe.samsung.gl
call adb shell pm disable-user --user 0	com.google.android.apps.carrier.carrierwifi
call adb shell pm disable-user --user 0	com.google.android.apps.restore
call adb shell pm disable-user --user 0	com.google.android.feedback
call adb shell pm disable-user --user 0	com.google.android.gms.location.history
call adb shell pm disable-user --user 0	com.google.android.googlequicksearchbox
call adb shell pm disable-user --user 0	com.google.android.onetimeinitializer
call adb shell pm disable-user --user 0	com.google.android.partnersetup
call adb shell pm disable-user --user 0	com.google.android.setupwizard
call adb shell pm disable-user --user 0	com.google.android.tts
call adb shell pm disable-user --user 0	com.hiya.star
call adb shell pm disable-user --user 0	com.monotype.android.font.foundation
call adb shell pm disable-user --user 0	com.osp.app.signin
call adb shell pm disable-user --user 0	com.samsung.aasaservice
call adb shell pm disable-user --user 0	com.samsung.android.accessibility.talkback
call adb shell pm disable-user --user 0	com.samsung.android.allshare.service.mediashare
call adb shell pm disable-user --user 0	com.samsung.android.app.appsedge
call adb shell pm disable-user --user 0	com.samsung.android.app.clipboardedge
call adb shell pm disable-user --user 0	com.samsung.android.app.cocktailbarservice
call adb shell pm disable-user --user 0	com.samsung.android.app.galaxyfinder
call adb shell pm disable-user --user 0	com.samsung.android.app.omcagent
call adb shell pm disable-user --user 0	com.samsung.android.app.settings.bixby
call adb shell pm disable-user --user 0	com.samsung.android.app.sharelive
call adb shell pm disable-user --user 0	com.samsung.android.app.updatecenter
call adb shell pm disable-user --user 0	com.samsung.android.app.watchmanagerstub
call adb shell pm disable-user --user 0	com.samsung.android.aware.service
call adb shell pm disable-user --user 0	com.samsung.android.beaconmanager
call adb shell pm disable-user --user 0	com.samsung.android.da.daagent
call adb shell pm disable-user --user 0	com.samsung.android.easysetup
call adb shell pm disable-user --user 0	com.samsung.android.fmm
call adb shell pm disable-user --user 0	com.samsung.android.gru
call adb shell pm disable-user --user 0	com.samsung.android.honeyboard
call adb shell pm disable-user --user 0	com.samsung.android.kgclient
call adb shell pm disable-user --user 0	com.samsung.android.kidsinstaller
call adb shell pm disable-user --user 0	com.samsung.android.mapsagent
call adb shell pm disable-user --user 0	com.samsung.android.mobileservice
call adb shell pm disable-user --user 0	com.samsung.android.providers.factory
call adb shell pm disable-user --user 0	com.samsung.android.rubin.app
call adb shell pm disable-user --user 0	com.samsung.android.scloud
call adb shell pm disable-user --user 0	com.samsung.android.sm.policy
call adb shell pm disable-user --user 0	com.samsung.android.smartmirroring
call adb shell pm disable-user --user 0	com.samsung.android.smartswitchassistant
call adb shell pm disable-user --user 0	com.samsung.android.stickercenter
call adb shell pm disable-user --user 0	com.samsung.android.themestore
call adb shell pm disable-user --user 0	com.samsung.ims.smk
call adb shell pm disable-user --user 0	com.sec.android.app.billing
call adb shell pm disable-user --user 0	com.sec.android.app.fm
call adb shell pm disable-user --user 0	com.sec.android.app.safetyassurance
call adb shell pm disable-user --user 0	com.sec.android.app.SecSetupWizard
call adb shell pm disable-user --user 0	com.sec.android.app.setupwizardlegalprovider
call adb shell pm disable-user --user 0	com.sec.android.easyMover.Agent
call adb shell pm disable-user --user 0	com.sec.android.easyonehand
call adb shell pm disable-user --user 0	com.sec.android.emergencylauncher
call adb shell pm disable-user --user 0	com.sec.android.emergencymode.service
call adb shell pm disable-user --user 0	com.sec.android.provider.emergencymode
call adb shell pm disable-user --user 0	com.sec.android.widgetapp.webmanual
call adb shell pm disable-user --user 0	com.sec.enterprise.mdm.services.simpin
call adb shell pm disable-user --user 0	com.sec.epdgtestapp
call adb shell pm disable-user --user 0	com.sec.mhs.smarttethering
call adb shell pm disable-user --user 0	com.sec.modem.settings
call adb shell pm disable-user --user 0	com.sec.spp.push
call adb shell pm disable-user --user 0	com.tplink.tether
call adb shell pm disable-user --user 0	com.val.hardware
call adb uninstall com.facebook.appmanager
call adb uninstall com.facebook.katana
call adb uninstall com.facebook.services
call adb uninstall com.facebook.system
call adb shell pm disable-user --user 0	com.google.android.apps.maps
call adb shell pm disable-user --user 0	com.google.android.apps.tachyon
call adb shell pm disable-user --user 0	com.google.android.projection.gearhead
call adb shell pm disable-user --user 0	com.microsoft.skydrive
call adb uninstall com.netflix.mediaclient
call adb shell pm disable-user --user 0	com.sec.android.app.samsungapps
call adb shell pm disable-user --user 0	com.sec.unifiedwfc
#call adb kill-server